name: gymtrack
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.0
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon1024.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Geologica
      fonts:
        - asset: assets/fonts/Geologica-Thin.ttf
          weight: 100
        - asset: assets/fonts/Geologica-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Geologica-Light.ttf
          weight: 300
        - asset: assets/fonts/Geologica-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geologica-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geologica-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Geologica-Bold.ttf
          weight: 700
        - asset: assets/fonts/Geologica-Black.ttf
          weight: 800
        - asset: assets/fonts/Geologica-ExtraBold.ttf
          weight: 900

  assets:
    - assets/icons/
    - assets/images/
    - assets/jsons/
    - assets/images/icons/
